apiVersion: apps/v1
kind: Deployment
metadata:
  name: weighttracker-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weighttracker
  template:
    metadata:
      labels:
        app: weighttracker
    spec:
      containers:
        - name: weighttracker
          image: gianniacquisto/weight-tracker
          imagePullPolicy: Always
          ports:
            - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: service-entrypoint
  namespace: default
spec:
  type: NodePort
  selector:
    app: weighttracker
  ports:
    - port: 8000
      nodePort: 30001
